# Generated by Django 5.1.5 on 2025-04-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_policyapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyApplication',
        ),
    ]
