# Generated by Django 3.0.5 on 2025-04-03 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_default_user(apps, schema_editor):
    """ Assign a default user to existing claims where user is NULL """
    Claims = apps.get_model('customer', 'Claims')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    default_user = User.objects.first()  # Pick the first user as default
    if default_user:
        Claims.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0012_auto_20250330_1510'),
    ]

    operations = [
        # Assign a default user before altering the field
        migrations.RunPython(assign_default_user),

        migrations.AlterField(
            model_name='claims',
            name='status',
            field=models.CharField(
                choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')],
                default='Pending',
                max_length=10
            ),
        ),
        migrations.AlterField(
            model_name='claims',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
