# Generated by Django 3.0.5 on 2025-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20250403_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='supporting_document',
            field=models.ImageField(blank=True, null=True, upload_to='claims/'),
        ),
    ]
